---
image: 'fedora'

before_script:
  - ./setup.sh

stages:
  - build
  - test

build:
  stage: build
  script:
    - HARDWARE_PLATFORM=x86_64 gprbuild axdg.gpr
  artifacts:
    paths:
      - bin/*
      - build/*
    expire_in: 1 week

test:
  stage: test
  script:
    - HARDWARE_PLATFORM=x86_64 ./test.sh

after_script:
  - echo "End CI"
